name: geolocator_ohos
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.8.0"


flutter:
  plugin:
    implements: geolocator
    platforms:
      ohos:
        package: com.baseflow.geolocator
        pluginClass: GeolocatorPlugin
        dartPluginClass: GeolocatorOhos

dependencies:
  flutter:
    sdk: flutter
  geolocator_platform_interface:
    path: ../geolocator_platform_interface
  meta: ^1.0.0
  uuid: ">=4.0.0 <6.0.0"

dev_dependencies:
  async: ^2.8.2
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <5.0.0"
  mockito: ^5.2.0
  plugin_platform_interface: ^2.1.2

