name: geolocator
description: Geolocation plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 11.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: geolocator_android
      ios:
        default_package: geolocator_apple
      ohos:
        default_package: geolocator_ohos
      macos:
        default_package: geolocator_apple
      web:
        default_package: geolocator_web
      windows:
        default_package: geolocator_windows
      linux:
        default_package: geolocator_linux

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface:
    path: ../geolocator_platform_interface
  geolocator_android:
    path: ../geolocator_android
  geolocator_apple:
    path: ../geolocator_apple
  geolocator_web:
    path: ../geolocator_web
  geolocator_windows:
    path: ../geolocator_windows
  geolocator_linux:
    path: ../geolocator_linux
  geolocator_ohos:
    path: ../geolocator_ohos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.3 <5.0.0"
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
